name: Uhcffa
version: ${project.version}
main: si.f5.hatosaba.uhcffa.Uhcffa
depend: [Essentials, PvPLevels, Triton]
softdepend: [PlaceholderAPI]

commands:
  duel:
    description: Main duel Command
  dueladmin:
    description: Main dueladmin Command
  accept:
    description: Main accept Command
  ffa:
    description: Main ffa Command
  inventory:
    description: Main inventory Command
  kit:
    description: Main kit Command